### ISSUE TITLE
2024.9.x - "Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fd085ec95d0>,) inside the event loop by custom integration 'kevo_plus'"

### ISSUE THREAD

**Issue by AnthonyBe** [gaggle331/home-assistant-kevo#17]
Since 2024.9 there's been a new warning logged.
Seeing this on a number of integrations, i.e. not limited to Kevo Plus integration.
Doesn't appear to be impacting integration performance at this stage.

```
2024-09-12 15:00:55.517 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fd085ec95d0>,) inside the event loop by custom integration 'kevo_plus' at custom_components/kevo_plus/__init__.py, line 37: await client.login(entry.data.get(CONF_USERNAME), password) (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 147: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/dcmeglio/home-assistant-kevo/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kevo_plus/__init__.py", line 37, in async_setup_entry
    await client.login(entry.data.get(CONF_USERNAME), password)
```
and a 2nd error

```
2024-09-12 15:01:06.071 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fd07a1b3ed0>,) in /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 147: context.load_verify_locations(cafile=cafile) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiokevoplus/__init__.py", line 482, in __websocket_connect
    snonce = await self.__get_server_nonce()
  File "/usr/local/lib/python3.12/site-packages/aiokevoplus/__init__.py", line 159, in __get_server_nonce
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1431, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1479, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 277, in __init__
    ssl_context = create_ssl_context(verify=verify, cert=cert, trust_env=trust_env)
  File "/usr/local/lib/python3.12/site-packages/httpx/_config.py", line 53, in create_ssl_context
    return SSLConfig(
  File "/usr/local/lib/python3.12/site-packages/httpx/_config.py", line 77, in __init__
    self.ssl_context = self.load_ssl_context()
  File "/usr/local/lib/python3.12/site-packages/httpx/_config.py", line 89, in load_ssl_context
    return self.load_ssl_context_verify()
  File "/usr/local/lib/python3.12/site-packages/httpx/_config.py", line 147, in load_ssl_context_verify
    context.load_verify_locations(cafile=cafile)
```

**Comment by AnthonyBe** [comment]
Updated versions of these errors with HA 2024.12 which had a python update.
@dcmeglio - any chance you are still active? As the person that coded the updated fork it would be awesome if you had some time to take a look.

**Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fea89c44ef0>,) inside the event loop by custom integration 'kevo_plus'**

```
2024-12-07 17:34:14.615 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fea89c44ef0>,) inside the event loop by custom integration 'kevo_plus' at custom_components/kevo_plus/__init__.py, line 37: await client.login(entry.data.get(CONF_USERNAME), password) (offender: /usr/local/lib/python3.13/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/dcmeglio/home-assistant-kevo/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 788, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kevo_plus/__init__.py", line 37, in async_setup_entry
    await client.login(entry.data.get(CONF_USERNAME), password)
```

and the 2nd error
**Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fea742c0200>,) in /usr/local/lib/python3.13/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile) inside the event loop**

```
2024-12-07 17:34:22.242 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fea742c0200>,) in /usr/local/lib/python3.13/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.13/site-packages/aiokevoplus/__init__.py", line 482, in __websocket_connect
    snonce = await self.__get_server_nonce()
  File "/usr/local/lib/python3.13/site-packages/aiokevoplus/__init__.py", line 159, in __get_server_nonce
    client = httpx.AsyncClient()
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1442, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1490, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 280, in __init__
    ssl_context = create_ssl_context(verify=verify, cert=cert, trust_env=trust_env)
  File "/usr/local/lib/python3.13/site-packages/httpx/_config.py", line 55, in create_ssl_context
    return SSLConfig(
  File "/usr/local/lib/python3.13/site-packages/httpx/_config.py", line 79, in __init__
    self.ssl_context = self.load_ssl_context()
  File "/usr/local/lib/python3.13/site-packages/httpx/_config.py", line 91, in load_ssl_context
    return self.load_ssl_context_verify()
  File "/usr/local/lib/python3.13/site-packages/httpx/_config.py", line 149, in load_ssl_context_verify
    context.load_verify_locations(cafile=cafile)
```

**Comment by AnthonyBe** [comment]
Just FYI, I've just submitted some PRs on https://github.com/dcmeglio/pykevoplus and https://github.com/dcmeglio/home-assistant-kevo that _might_ fix these blocking call warnings.

Hoping the repo owner sees the Github notifications and has time to look at them!
